version: '3.8'

services:
  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - graphql-db
    environment:
      QUARKUS_PROFILE: dev
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://graphql-db:5432/graphql
      QUARKUS_DATASOURCE_USERNAME: your-username
      QUARKUS_DATASOURCE_PASSWORD: your-password

  graphql-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: graphql
      POSTGRES_USER: your-username
      POSTGRES_PASSWORD: your-password
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/import.sql:/docker-entrypoint-initdb.d/init.sql
