FROM maven:3.8.4-openjdk-17 AS build

WORKDIR /app

COPY pom.xml /app/
COPY src /app/src

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /work/application

COPY --from=build /app/target/*-runner.jar /work/application/application.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/work/application/application.jar"]
